<a href="https://colab.research.google.com/github/DrStephPowers/BIA/blob/main/Ch5_DescriptiveStatistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import scipy.stats as stats

Mount Drive (replace by access to Github)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Import Data

In [ ]:
df = pd.read_excel('/content/drive/MyDrive/BI BA Handbook/Chapter 4/bargainclean.xlsx')

## Preview Table

Shows the first four rows of the table called df

In [ ]:
df.head(4)

,Respondent,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8a,Q8b,...,Q15,Q16,Q17,Q18,Q19,Q20,Q21,Q22,Q23,Q24
0,1,Increasing pay,Full Time,3.0,Additional funding for Counselling,No,1,No,1,3,...,4,NaN,0.0,4,Better lighting in the parking lot,4,More women in leadership positions,Yes,East,15.0
1,2,Improve benefits,Full Time,1.0,Drug coverage,Yes,3,Yes,3,4,...,2,Be able to work from home once a week,0.0,3,NaN,4,NaN,No,North,2.0
2,3,Job security,Part Time,NaN,NaN,No,1,No,3,1,...,3,Give me more hours,0.0,3,NaN,5,NaN,No,North,NaN
3,4,Job security,Part Time,NaN,NaN,I don't know,4,No,3,2,...,2,more flexibility on work from home for part time,0.0,4,NaN,4,NaN,Yes,East,1.0

## Frequency

In [ ]:
df.value_counts("Q2")

Q2
Full Time    43
Part Time    20
dtype: int64

## Percentages

In [ ]:
df.value_counts("Q2", normalize=True)

Q2
Full Time    0.68254
Part Time    0.31746
dtype: float64

Switch to Coded Dataset

In [ ]:
df2 = pd.read_excel('/content/drive/MyDrive/BI BA Handbook/Chapter 4/bargainnumeric.xlsx')

Preview the dataset

In [ ]:
df2.head(4)

,Respondent,Q1,Q2,Q3,Q4a,Q5,Q6,Q7,Q8a,Q8b,...,Q13,Q14,Q15,Q17,Q18,Q20,Q22,Q23,Q24,Q24a
0,1,5,2,3.0,7.0,2,1,2,1,3,...,4,4,4,0.0,4,4,1,3,15.0,3.0
1,2,1,2,1.0,6.0,1,3,1,3,4,...,3,1,2,0.0,3,4,2,1,2.0,1.0
2,3,3,1,NaN,NaN,2,1,2,3,1,...,1,3,3,0.0,3,5,2,1,NaN,NaN
3,4,3,1,NaN,NaN,3,4,2,3,2,...,5,4,2,0.0,4,4,1,3,1.0,1.0

Counts for All Variables

In [ ]:
df2.apply(df2.value_counts)

,Respondent,Q1,Q2,Q3,Q4a,Q5,Q6,Q7,Q8a,Q8b,...,Q13,Q14,Q15,Q17,Q18,Q20,Q22,Q23,Q24,Q24a
0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,45.0,NaN,NaN,NaN,NaN,NaN,NaN
1.0,1.0,14.0,20.0,2.0,15.0,22.0,5.0,20.0,5.0,13.0,...,4.0,2.0,3.0,NaN,4.0,2.0,16.0,18.0,6.0,33.0
2.0,1.0,19.0,43.0,14.0,1.0,26.0,28.0,42.0,12.0,23.0,...,13.0,7.0,15.0,NaN,5.0,12.0,40.0,22.0,13.0,11.0
3.0,1.0,10.0,NaN,10.0,2.0,15.0,20.0,1.0,13.0,19.0,...,14.0,18.0,19.0,NaN,23.0,23.0,7.0,23.0,7.0,6.0
4.0,1.0,NaN,NaN,16.0,NaN,NaN,10.0,NaN,11.0,1.0,...,27.0,32.0,21.0,1.0,30.0,24.0,NaN,NaN,5.0,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Percentages for All Variables

In [ ]:
df2.apply(df2.value_counts, normalize=True)

,Respondent,Q1,Q2,Q3,Q4a,Q5,Q6,Q7,Q8a,Q8b,...,Q13,Q14,Q15,Q17,Q18,Q20,Q22,Q23,Q24,Q24a
0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.750000,NaN,NaN,NaN,NaN,NaN,NaN
1.0,0.015873,0.222222,0.31746,0.046512,0.348837,0.349206,0.079365,0.317460,0.079365,0.206349,...,0.063492,0.031746,0.047619,NaN,0.063492,0.031746,0.253968,0.285714,0.096774,0.532258
2.0,0.015873,0.301587,0.68254,0.325581,0.023256,0.412698,0.444444,0.666667,0.190476,0.365079,...,0.206349,0.111111,0.238095,NaN,0.079365,0.190476,0.634921,0.349206,0.209677,0.177419
3.0,0.015873,0.158730,NaN,0.232558,0.046512,0.238095,0.317460,0.015873,0.206349,0.301587,...,0.222222,0.285714,0.301587,NaN,0.365079,0.365079,0.111111,0.365079,0.112903,0.096774
4.0,0.015873,NaN,NaN,0.372093,NaN,NaN,0.158730,NaN,0.174603,0.015873,...,0.428571,0.507937,0.333333,0.016667,0.476190,0.380952,NaN,NaN,0.080645,0.193548
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59.0,0.015873,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60.0,0.015873,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61.0,0.015873,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62.0,0.015873,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63.0,0.015873,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Condense table

In [ ]:
perc = df2.apply(df2.value_counts, normalize=True)
perc2 = perc.tail(-1)
perc2.head(7)

,Respondent,Q1,Q2,Q3,Q4a,Q5,Q6,Q7,Q8a,Q8b,...,Q13,Q14,Q15,Q17,Q18,Q20,Q22,Q23,Q24,Q24a
1.0,0.015873,0.222222,0.31746,0.046512,0.348837,0.349206,0.079365,0.317460,0.079365,0.206349,...,0.063492,0.031746,0.047619,NaN,0.063492,0.031746,0.253968,0.285714,0.096774,0.532258
2.0,0.015873,0.301587,0.68254,0.325581,0.023256,0.412698,0.444444,0.666667,0.190476,0.365079,...,0.206349,0.111111,0.238095,NaN,0.079365,0.190476,0.634921,0.349206,0.209677,0.177419
3.0,0.015873,0.158730,NaN,0.232558,0.046512,0.238095,0.317460,0.015873,0.206349,0.301587,...,0.222222,0.285714,0.301587,NaN,0.365079,0.365079,0.111111,0.365079,0.112903,0.096774
4.0,0.015873,NaN,NaN,0.372093,NaN,NaN,0.158730,NaN,0.174603,0.015873,...,0.428571,0.507937,0.333333,0.016667,0.476190,0.380952,NaN,NaN,0.080645,0.193548
5.0,0.015873,0.317460,NaN,0.023256,0.093023,NaN,NaN,NaN,0.047619,0.031746,...,0.079365,0.063492,0.079365,0.116667,0.015873,0.031746,NaN,NaN,0.032258,NaN
6.0,0.015873,NaN,NaN,NaN,0.372093,NaN,NaN,NaN,0.301587,0.079365,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.080645,NaN
7.0,0.015873,NaN,NaN,NaN,0.116279,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.032258,NaN

## Mode

Mode from Original Dataset

Axis = 0 indicates that the mode is found for each column. Axis = 1 would give the mode by row.

Mode can be restricted to only numeric columns. If you have coded the survey, then use numeric_only=TRUE so that it doesn't show the open ended responses. The reason the information below contains rows of NaN is because it is showing each unique response for the open ended questions (all responses tie for a mode of 1).

In [ ]:
df.mode(axis=0, numeric_only=False, dropna=True)

,Respondent,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8a,Q8b,...,Q15,Q16,Q17,Q18,Q19,Q20,Q21,Q22,Q23,Q24
0,1,Increasing pay,Full Time,4.0,Drug coverage,No,2.0,No,6.0,2.0,...,4.0,more hours,0.0,4.0,Better lighting in the parking lot,4.0,Celebration of holidays of multiple religions ...,No,East,2.0
1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,More women in leadership positions,NaN,NaN,NaN
2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Visible minorities are not given same project ...,NaN,NaN,NaN
3,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,equal opportunity for projects,NaN,NaN,NaN
4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,greater opportunities for people to move up in...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Mode from Coded Data

Notice that the mode for Q2 previously was Full Time. Recall that Part Time was coded as 1 and Full Time was coded as 2. Below the mode for Q2 is 2.

An additional line of code was added to show only the first row. The 62 rows of NaN aren't needed.

A third line of code allows for the data to be transposed. Otherwise, the varibles are listed as columns, which is inconsistent with the other descriptive statistics.

In [ ]:
df2_mode1 = df2.mode(axis=0, numeric_only=True, dropna=True)
df2_mode2 = df2_mode1.head(1)
df2_mode = df2_mode2.T
print(df2_mode)

              0
Respondent  1.0
Q1          5.0
Q2          2.0
Q3          4.0
Q4a         6.0
Q5          2.0
Q6          2.0
Q7          2.0
Q8a         6.0
Q8b         2.0
Q8c         6.0
Q8d         4.0
Q8e         6.0
Q8f         1.0
Q10         2.0
Q11         2.0
Q12         2.0
Q13         4.0
Q14         4.0
Q15         4.0
Q17         0.0
Q18         4.0
Q20         4.0
Q22         2.0
Q23         3.0
Q24         2.0
Q24a        1.0

Mode for Just One Variable

In [ ]:
df2['Q2'].mode()

0    2
Name: Q2, dtype: int64

## Median

In [ ]:
df2['Q6'].median()

2.0

In [ ]:
df2.median()

Respondent    32.0
Q1             2.0
Q2             2.0
Q3             3.0
Q4a            5.0
Q5             2.0
Q6             2.0
Q7             2.0
Q8a            4.0
Q8b            2.0
Q8c            5.0
Q8d            4.0
Q8e            6.0
Q8f            1.0
Q10            2.0
Q11            2.0
Q12            2.0
Q13            4.0
Q14            4.0
Q15            3.0
Q17            0.0
Q18            3.0
Q20            3.0
Q22            2.0
Q23            2.0
Q24            4.5
Q24a           1.0
dtype: float64

Mean

In [ ]:
df2['Q24'].mean()

8.387096774193548

In [ ]:
df2.mean()

Respondent    32.000000
Q1             2.888889
Q2             1.682540
Q3             3.000000
Q4a            4.046512
Q5             1.888889
Q6             2.555556
Q7             1.698413
Q8a            3.825397
Q8b            2.539683
Q8c            4.612903
Q8d            3.698413
Q8e            5.532258
Q8f            1.873016
Q10            2.380952
Q11            2.333333
Q12            1.952381
Q13            3.253968
Q14            3.460317
Q15            3.158730
Q17            2.183333
Q18            3.301587
Q20            3.190476
Q22            1.857143
Q23            2.079365
Q24            8.387097
Q24a           1.951613
dtype: float64

## Min

In [ ]:
df2.min()

Respondent    1.0
Q1            1.0
Q2            1.0
Q3            1.0
Q4a           1.0
Q5            1.0
Q6            1.0
Q7            1.0
Q8a           1.0
Q8b           1.0
Q8c           1.0
Q8d           1.0
Q8e           1.0
Q8f           1.0
Q10           1.0
Q11           1.0
Q12           1.0
Q13           1.0
Q14           1.0
Q15           1.0
Q17           0.0
Q18           1.0
Q20           1.0
Q22           1.0
Q23           1.0
Q24           1.0
Q24a          1.0
dtype: float64

## Max

In [ ]:
df2.max()

Respondent    63.0
Q1             5.0
Q2             2.0
Q3             5.0
Q4a            7.0
Q5             3.0
Q6             4.0
Q7             3.0
Q8a            6.0
Q8b            6.0
Q8c            6.0
Q8d            6.0
Q8e            6.0
Q8f            6.0
Q10            5.0
Q11            4.0
Q12            4.0
Q13            5.0
Q14            5.0
Q15            5.0
Q17           20.0
Q18            5.0
Q20            5.0
Q22            3.0
Q23            3.0
Q24           30.0
Q24a           4.0
dtype: float64

## Range

In [ ]:
df2.max()-df2.min()

Respondent    62.0
Q1             4.0
Q2             1.0
Q3             4.0
Q4a            6.0
Q5             2.0
Q6             3.0
Q7             2.0
Q8a            5.0
Q8b            5.0
Q8c            5.0
Q8d            5.0
Q8e            5.0
Q8f            5.0
Q10            4.0
Q11            3.0
Q12            3.0
Q13            4.0
Q14            4.0
Q15            4.0
Q17           20.0
Q18            4.0
Q20            4.0
Q22            2.0
Q23            2.0
Q24           29.0
Q24a           3.0
dtype: float64

## Interquartile Range

In [ ]:
Q1 = df2.quantile(0.25)
Q3 = df2.quantile(0.75)
Q3-Q1

Respondent    31.00
Q1             3.00
Q2             1.00
Q3             2.00
Q4a            5.00
Q5             1.00
Q6             1.00
Q7             1.00
Q8a            4.00
Q8b            1.00
Q8c            2.00
Q8d            1.50
Q8e            0.00
Q8f            1.50
Q10            1.00
Q11            1.00
Q12            1.00
Q13            2.00
Q14            1.00
Q15            2.00
Q17            1.00
Q18            1.00
Q20            1.00
Q22            0.50
Q23            2.00
Q24            9.75
Q24a           2.00
dtype: float64

## Standard Deviation

In [ ]:
df2.std()

Respondent    18.330303
Q1             1.577167
Q2             0.469227
Q3             1.000000
Q4a            2.458740
Q5             0.764349
Q6             0.857186
Q7             0.496274
Q8a            1.718398
Q8b            1.365773
Q8c            1.653162
Q8d            1.172740
Q8e            1.141149
Q8f            1.373623
Q10            1.169899
Q11            0.950382
Q12            0.957628
Q13            1.077157
Q14            0.894885
Q15            1.034975
Q17            4.522980
Q18            0.891445
Q20            0.895457
Q22            0.591803
Q23            0.809253
Q24            8.435590
Q24a           1.193252
dtype: float64

## Summary Statistics

Creating a table of Summary Statitics

In [ ]:
df2_mode1 = df2.mode(axis=0, numeric_only=True, dropna=True)
df2_mode2 = df2_mode1.head(1)
df2_mode = df2_mode2.T

df2_range = df2.max()-df2.min()

Q1 = df2.quantile(0.25)
Q3 = df2.quantile(0.75)
df2_IQR = Q3-Q1

df_summary = pd.DataFrame()
df_summary["Min"] = df2.min()
df_summary["Max"] = df2.max()
df_summary["Mode"] = df2_mode
df_summary["Median"] = df2.median()
df_summary["Mean"] = df2.mean()
df_summary["Range"] = df2_range
df_summary["IQR"] = df2_IQR
df_summary["Std Dev"] = df2.std()
print(df_summary)

            Min   Max  Mode  Median       Mean  Range    IQR    Std Dev
Respondent  1.0  63.0   1.0    32.0  32.000000   62.0  31.00  18.330303
Q1          1.0   5.0   5.0     2.0   2.888889    4.0   3.00   1.577167
Q2          1.0   2.0   2.0     2.0   1.682540    1.0   1.00   0.469227
Q3          1.0   5.0   4.0     3.0   3.000000    4.0   2.00   1.000000
Q4a         1.0   7.0   6.0     5.0   4.046512    6.0   5.00   2.458740
Q5          1.0   3.0   2.0     2.0   1.888889    2.0   1.00   0.764349
Q6          1.0   4.0   2.0     2.0   2.555556    3.0   1.00   0.857186
Q7          1.0   3.0   2.0     2.0   1.698413    2.0   1.00   0.496274
Q8a         1.0   6.0   6.0     4.0   3.825397    5.0   4.00   1.718398
Q8b         1.0   6.0   2.0     2.0   2.539683    5.0   1.00   1.365773
Q8c         1.0   6.0   6.0     5.0   4.612903    5.0   2.00   1.653162
Q8d         1.0   6.0   4.0     4.0   3.698413    5.0   1.50   1.172740
Q8e         1.0   6.0   6.0     6.0   5.532258    5.0   0.00   1.141149
Q8f         1.0   6.0   1.0     1.0   1.873016    5.0   1.50   1.373623
Q10         1.0   5.0   2.0     2.0   2.380952    4.0   1.00   1.169899
Q11         1.0   4.0   2.0     2.0   2.333333    3.0   1.00   0.950382
Q12         1.0   4.0   2.0     2.0   1.952381    3.0   1.00   0.957628
Q13         1.0   5.0   4.0     4.0   3.253968    4.0   2.00   1.077157
Q14         1.0   5.0   4.0     4.0   3.460317    4.0   1.00   0.894885
Q15         1.0   5.0   4.0     3.0   3.158730    4.0   2.00   1.034975
Q17         0.0  20.0   0.0     0.0   2.183333   20.0   1.00   4.522980
Q18         1.0   5.0   4.0     3.0   3.301587    4.0   1.00   0.891445
Q20         1.0   5.0   4.0     3.0   3.190476    4.0   1.00   0.895457
Q22         1.0   3.0   2.0     2.0   1.857143    2.0   0.50   0.591803
Q23         1.0   3.0   3.0     2.0   2.079365    2.0   2.00   0.809253
Q24         1.0  30.0   2.0     4.5   8.387097   29.0   9.75   8.435590
Q24a        1.0   4.0   1.0     1.0   1.951613    3.0   2.00   1.193252

## Built in Summary Statistics

The 50 percent listed below is the median.

In [ ]:
df2.describe()

,Respondent,Q1,Q2,Q3,Q4a,Q5,Q6,Q7,Q8a,Q8b,...,Q13,Q14,Q15,Q17,Q18,Q20,Q22,Q23,Q24,Q24a
count,63.000000,63.000000,63.000000,43.0,43.000000,63.000000,63.000000,63.000000,63.000000,63.000000,...,63.000000,63.000000,63.000000,60.000000,63.000000,63.000000,63.000000,63.000000,62.000000,62.000000
mean,32.000000,2.888889,1.682540,3.0,4.046512,1.888889,2.555556,1.698413,3.825397,2.539683,...,3.253968,3.460317,3.158730,2.183333,3.301587,3.190476,1.857143,2.079365,8.387097,1.951613
std,18.330303,1.577167,0.469227,1.0,2.458740,0.764349,0.857186,0.496274,1.718398,1.365773,...,1.077157,0.894885,1.034975,4.522980,0.891445,0.895457,0.591803,0.809253,8.435590,1.193252
min,1.000000,1.000000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,16.500000,2.000000,1.000000,2.0,1.000000,1.000000,2.000000,1.000000,2.000000,2.000000,...,2.000000,3.000000,2.000000,0.000000,3.000000,3.000000,1.500000,1.000000,2.000000,1.000000
50%,32.000000,2.000000,2.000000,3.0,5.000000,2.000000,2.000000,2.000000,4.000000,2.000000,...,4.000000,4.000000,3.000000,0.000000,3.000000,3.000000,2.000000,2.000000,4.500000,1.000000
75%,47.500000,5.000000,2.000000,4.0,6.000000,2.000000,3.000000,2.000000,6.000000,3.000000,...,4.000000,4.000000,4.000000,1.000000,4.000000,4.000000,2.000000,3.000000,11.750000,3.000000
max,63.000000,5.000000,2.000000,5.0,7.000000,3.000000,4.000000,3.000000,6.000000,6.000000,...,5.000000,5.000000,5.000000,20.000000,5.000000,5.000000,3.000000,3.000000,30.000000,4.000000